Fix: add auto_estimate=True to transfer_on_l2()
The prepare_invoke() call in transfer_on_l2() was missing the auto_estimate
parameter after random_resource_bounds() was removed. This caused transfers
to fail with starknet-py 0.28.x which requires either resource_bounds or
auto_estimate to be specified.

Error before fix:
ValueError: One of arguments: resource_bounds or auto_estimate must be specified
when invoking a transaction.